version: '3.7'

services:
  twirl:
    build:
      context: .
    image: twirl
    container_name: twirl
    user: ${CURRENT_UID} # https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15
    environment:
      - DISPLAY
    network_mode: 'host'
    volumes:
      - .:/app
      - /app/node_modules # prevents the container from polluting local directory
      - "$HOME/.Xauthority:/home/node/.Xauthority:rw" # Share the X Server with the container
    command: 'tail -f /dev/null'
